# 基础设置
# 导航抽屉里的头像
avatar: images/avatar.JPG

# 是否开启分类页面
category: true

# 是否开启标签页面
tag: true

# 是否开启归档页面
archive: true

# 是否使用自定义favicon
favicon: images/favicon.ico

#############################################################

# 主题相关
# 是否使用自定义主题色 支持16进制颜色码，注意前面的井号（#）要转义 默认深紫色
primaryColor: \#6200ea
# 是否使用自定义顶栏颜色 取消注释表示启用
# appBarColor: \#ffffff
# 是否使用亮色顶栏，如果你的顶栏颜色是亮色的话请启用 取消注释表示启用
# useLightAppBar: true
# 是否在顶栏中插入背景，需要提供背景图片的路径 取消注释表示启用
appBarBackground: images/test-background.png
# 是否拓展顶栏高度，滑动后会折叠至正常高度，建议在有顶栏背景时启用 取消注释表示启用
useLargerHeightOfAppBar: true
# 折叠至正常高度后是否将顶栏过度成纯色 取消注释表示启用
fadeOutToPureColor: true