# 基础设置
# 导航抽屉里的头像
avatar: images/avatar.JPG

# 是否开启分类页面
category: true

# 是否开启标签页面
tag: true

# 是否开启归档页面
archive: true

# 是否使用自定义favicon 取消注释表示启用
# favicon: images/favicon-default.png

# 始于YYYY年
since: 2019

# 显示夜间模式切换按钮
showDarkModeSwitch: true

# 开启自动夜间模式
autoSwitchToDarkMode: true

#############################################################

# 主题相关
# 样式，默认扁平样式，将值改为normal可启用正常样式
scheme: flat
# 不使用主题色，在扁平样式下本设置无效，主题色参考MDUI文档：https://www.mdui.org/docs/color
primaryColor: none
# 导航，默认抽屉式导航，将值改为tab可将导航移动至顶部应用栏
navigation: drawer

#############################################################

# 高级功能
# 是否启用评论区，目前只支持来必力
comments: livere
commentsUID: MTAyMC80OTUwMy8yNTk5NA==